FROM node:16
RUN npm install -g cross-env
RUN mkdir -p /srv/app
WORKDIR /srv/app
RUN npm i -g @nestjs/cli 

COPY package*.json ./
RUN npm install 
COPY . .
EXPOSE 5000

CMD ["npm", "run", "start:dev"]